# Copyright 2023 Observational Health Data Sciences and Informatics
#
# This file is part of PatientLevelPredictionModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code:
# styler::style_dir()
# OhdsiRTools::updateCopyrightYearFolder()
# OhdsiRTools::findNonAsciiStringsInFolder()

# Generate settings function
moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
message(sprintf("Using module version '%s' in settings function.", moduleInfo$Version))
library(DeepPatientLevelPrediction)
rCode <- c("# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. ")
rCode <- c(rCode, readLines("extras/SettingsFunctionsStub.R"))
rCode <- gsub("%module%", moduleInfo$Name, rCode)
rCode <- gsub("%version%", moduleInfo$Version, rCode)
writeLines(rCode, "SettingsFunctions.R")

# Generate renv lock file and activate renv:
renv::deactivate()
OhdsiRTools::createRenvLockFile(
  rootPackage = "DeepPatientLevelPrediction",
  includeRootPackage = TRUE,
  mode = "description",
  additionalRequiredPackages = c(
    "DatabaseConnector",
    "checkmate",
    "CirceR",
    "testthat",
    "Eunomia"
  )
)
renv::init()
